In [3]:
import cv2

In [4]:
#image representation in a computer system
def main():
    imgpath='C:\\Users\\kenneth\\opencv\\dataset\\4.1.03.tiff'
    img=cv2.imread(imgpath, 0)
    print(img)
    print(type(img))
    print(img.dtype)
    print(img.shape)
    print(img.ndim)
    print(img.size)
#     cv2.imshow('lena',img)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()
    
    
if __name__ == "__main__":
    main()

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 216 218 217]
 [222 223 224 ... 230 229 229]
 ...
 [254 255 255 ... 255 255 254]
 [254 255 255 ... 255 255 255]
 [254 254 255 ... 255 255 255]]
<class 'numpy.ndarray'>
uint8
(256, 256)
2
65536
